@startuml
'https://plantuml.com/object-diagram

 object "ships : Ship[]" as ships

 object "ship1 : Ship" as ship1 {
     name = "Veil"
     yearShipBuilt = "2075"
 }

 object "ship2 : CruiseShip" as ship2 {
     name = "Titanic"
     yearShipBuilt = "1950"
     maxNumPassengers = 3000
 }

 object "ship3 : CargoShip" as ship3 {
     name = "Aziz"
     yearShipBuilt = "2026"
     cargoCapacity = 200
 }

 ships --> ship1 : [0]
 ships --> ship2 : [1]
 ships --> ship3 : [2]

 @enduml