@startuml
'https://plantuml.com/class-diagram

class Course {
    - courseName : String
    - instructor1 : Instructor
    - instructor2 : Instructor
    - textbook1 : Textbook
    - textbook2 : Textbook

    + Course(courseName : String, instructor1 : Instructor, instructor2 : Instructor, textbook1 : Textbook, textbook2 : Textbook)

    + getCourseName() : String
    + getInstructor1() : Instructor
    + getInstructor2() : Instructor
    + getTextbook1() : Textbook
    + getTextbook2() : Textbook

    + setCourseName(courseName : String) : void
    + setInstructor1(instructor1 : Instructor) : void
    + setInstructor2(instructor2 : Instructor) : void
    + setTextbook1(textbook1 : Textbook) : void
    + setTextbook2(textbook2 : Textbook) : void

    + print() : void
}

class Instructor {
    - firstName : String
    - lastName : String
    - officeNumber : String

    + Instructor(firstName : String, lastName : String, officeNumber : String)

    + getFirstName() : String
    + getLastName() : String
    + getOfficeNumber() : String

    + setFirstName(firstName : String) : void
    + setLastName(lastName : String) : void
    + setOfficeNumber(officeNumber : String) : void
}

class Textbook {
    - title : String
    - author : String
    - publisher : String

    + Textbook(title : String, author : String, publisher : String)

    + getTitle() : String
    + getAuthor() : String
    + getPublisher() : String

    + setTitle(title : String) : void
    + setAuthor(author : String) : void
    + setPublisher(publisher : String) : void
}

Course "1" o-- "2" Instructor
Course "1" o-- "2" Textbook

@enduml